site_name: Science IT Documentation

nav:
  - Home: index.md
  - High Performance Computing:
      - Account: 
          - Getting an Account: hpc/accounts/mylrc.md
          - Logging in: hpc/accounts/loggingin.md
          - Policies: hpc/accounts/policies.md
      - Running Jobs:
          - Slurm Overview: hpc/running/slurm_overview.md
          - Example Scripts: hpc/running/script_examples.md
          - Monitor Jobs: hpc/running/monitor_jobs.md
          - GNU Parallel: hpc/running/gnu_parallel.md
      - Software:
          - Software Module Farm: hpc/software/software-module-farm.md
          - Module Management: hpc/software/module-management.md
      - Frequently Asked Questions: hpc/faqs.md
      - Tutorials:
          - Using GPU on Jupyter: tutorials/jupyter_gpu.ipynb
      - Training and Workshops: training.md
      - Scientific Virtual Machines: construction.md
      - Data Center Co-Location: construction.md
      - Supported Research Clusters: construction.md
  - Data Transfer & Storage:
      - Data Transfer: data/datatransfer_node.md
      - Globus at Berkeley Lab: data/globus.md
      - Research Data Management: data/researchdata.md
      - Scientific Project Storage Service: data/spss.md
  - Cloud Computing:
      - Cloud Overview: cloud/index.md
      - Google Cloud Platform: cloud/gcp.md
      - Amazon Web Services: cloud/aws.md

plugins:
  - search
  - mkdocs-jupyter

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: custom
  logo: assets/scienceitlogo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.path
    - announce.dismiss
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
