site_name: Science IT Technical Documentation

nav:
  - Home: index.md
  - High Performance Computing:
      - Lawrencium Overview: hpc/index.md
      - Live Cluster Status: hpc/status.md
      - Getting Started: hpc/getting-started.md
      - Frequently Asked Questions: hpc/faqs.md
      - Account Management:
          - Project Accounts: hpc/accounts/project-accounts.md
          - User Accounts: hpc/accounts/user-accounts.md
          - Logging in: hpc/accounts/loggingin.md
          - Multi-Factor Authentication: hpc/accounts/mfa.md
      - Computing Systems:
          - Lawrencium: hpc/systems/lawrencium.md
          - Einsteinium GPU Cluster: hpc/systems/einsteinium.md
          - Californium: hpc/systems/californium.md
          - Curium AMD Cluster: hpc/systems/curium.md
          - Supported Research Clusters:
              - Secure Data Research Computing (SDRC): construction.md
              - ALSACC: hpc/systems/supported/alsacc.md
              - CATAMOUNT: hpc/systems/supported/catamount.md
      - Data Transfer:
          - Using the lrc-xfer DTN: hpc/datatransfer_node.md
          - Using Globus: hpc/globus_instructions.md
          - Rclone on Lawrencium: hpc/globus_instructions.md
          - SPSS on Lawrencium: hpc/globus_instructions.md          
      - Running Jobs:
          - Slurm Overview: hpc/running/slurm_overview.md
          - Example Scripts: hpc/running/script_examples.md
          - Monitor Jobs: hpc/running/monitor_jobs.md
          - Module Management: hpc/software/module-management.md
          - GNU Parallel: hpc/running/gnu_parallel.md
      - Using Open OnDemand:
          - Open OnDemand Overview: hpc/openondemand/overview.md
          - Jupyter Server: hpc/openondemand/jupyter-server.md
          - Adding Packages and Kernels: hpc/openondemand/packages-kernels.md
          - Using GPU on Jupyter: tutorials/jupyter_gpu.ipynb
      #- Scientific Virtual Machines (SVM):
      #    - SVM Overview: construction.md
      - Training and Workshops: training.md
  - Globus Transfer System:
      - Globus Transfer System Overview: data/index.md
      - Globus at Berkeley Lab: data/globus.md
      - Globus Personal: construction.md
      - Globus on Lawrencium: hpc/globus_instructions.md
      - Globus with Google Drive: construction.md
      - Globus with Google Cloud Storage: construction.md
      - Globus with AWS S3: construction.md
      - Globus Guest Collections: construction.md
      - Globus Connect Server: data/globus.md
      #- Globus with Scientific Project Storage Service (SPSS): data/spss.md
  #- Cloud Services:
  #    - Cloud Overview: cloud/index.md
  #    - Cloud Cost Comparisons: construction.md
  #    - Cloud Service Providers:
  #        - Google Cloud Platform: cloud/gcp.md
  #        - Amazon Web Services: cloud/aws.md
  #        - Microsoft Azure Cloud: construction.md
  #    - Cloud User Support: construction.md
  #    - Cloud Training Resources: construction.md
  #- Services:
  #    - Scientific Virtual Machines (SVM): construction.md
  #    - Scientific Project Storage System (SPSS): construction.md
  #    - Data Center Co-Location: construction.md
  #    - Research Cluster Support: construction.md
  #    - Software Module Farm: hpc/software/software-module-farm.md
  #    - Cloud Computing Services: construction.md
  #    - Science IT Consulting: construction.md
  #- AI:
  #    - GPU: construction.md
  #    - ChatGPT: construction.md
  #    - Inferencing 
  - Scientific Computing Demos:
      - Scientific Computing Demos Overview: demos/index.md
      - Intro to Data Science for Postdocs: construction.md
  - Support & Training: 
      - Dryad Publication Platform: construction.md
      - HPC Help Desk: help.md
      - Consulting Services: construction.md
      - LabTech Conference: construction.md
      - Presentations: construction.md
      - UC Berkeley DLab Workshops: construction.md

plugins:
  - search
  - mkdocs-jupyter
  - macros

extra:
  ext: <svg viewBox="0 0 1024 768" preserveAspectRatio="xMidYMid meet" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="#64666A" d="M640 768H128V257.90599999999995L256 256V128H0v768h768V576H640V768zM384 128l128 128L320 448l128 128 192-192 128 128V128H384z"/></svg>
  analytics:
    provider: google
    property: G-FKL0607RGR

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: custom
  logo: assets/scienceitlogo.png
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.tabs

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
