site_name: Science IT @ LBNL

nav:
  - Home: index.md
  - High Performance Computing:
      - Account:
          - Getting an Account: hpc/accounts/mylrc.md
          - Logging in: hpc/accounts/loggingin.md
          - Policies: hpc/accounts/policies.md
      - Running Jobs:
          - Slurm Overview: hpc/running/slurm_overview.md
          - Example Scripts: hpc/running/script_examples.md
          - Monitor Jobs: hpc/running/monitor_jobs.md
          - GNU Parallel: hpc/running/gnu_parallel.md
      - Software:
          - Software Module Farm: hpc/software/software-module-farm.md
          - Module Management: hpc/software/module-management.md
      - Frequently Asked Questions: hpc/faqs.md
      - Tutorials:
          - Using GPU on Jupyter: tutorials/jupyter_gpu.ipynb
      - Training and Workshops: training.md
      - Scientific Virtual Machines: construction.md
      - Data Center Co-Location: construction.md
      - Supported Research Clusters: construction.md
      - Secure Computing: construction.md
      - Live Cluster Status: hpc/status.md
  - Data Transfer & Storage:
      - Data Transfer: data/datatransfer_node.md
      - Globus at Berkeley Lab: data/globus.md
      - Globus Instructions: data/globus_instructions.md
      - Scientific Project Storage Service: data/spss.md
  - Cloud Computing:
      - Cloud Overview: cloud/index.md
      - Google Cloud Platform: cloud/gcp.md
      - Amazon Web Services: cloud/aws.md
  - Help: help.md

plugins:
  - search
  - mkdocs-jupyter
  - macros

extra:
  ext: <svg viewBox="0 0 1024 768" preserveAspectRatio="xMidYMid meet" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M640 768H128V257.90599999999995L256 256V128H0v768h768V576H640V768zM384 128l128 128L320 448l128 128 192-192 128 128V128H384z"/></svg>

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: custom
  logo: assets/scienceitlogo.png
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
